### ISSUE TITLE
Missing "Required" declaration in `utils.ts` of `ULTIMATE-REACT-COMPONENT-PATTERNS`

### ISSUE THREAD

**Issue by jacobbubu** [Hotell/blogposts#1]
https://github.com/Hotell/blogposts/blob/69d77bfa74ce7047a9aeeb4c88bb433606f2fbd6/2018-02/ultimate-react-component-patterns/src/utils.ts#L19

**Comment by Hotell** [comment]
nope, it's part of standard library :) 
https://github.com/Microsoft/TypeScript/blob/master/src/lib/es5.d.ts#L1341
