### ISSUE TITLE
Cannot find name 'Constructor'.

### ISSUE THREAD

**Issue by ahungrynoob** [Hotell/blogposts#14]
static ofType

**Comment by dfee** [comment]
Ok, it's actually defined in `globals.ts`: https://github.com/Hotell/blogposts/blob/e331a4e9c0f8bff4c346a1aa5aba1f6697a921d7/2018-02/ultimate-react-component-patterns/src/globals.d.ts#L3

**Comment by ahungrynoob** [comment]
@dfee yep
